name: Enhancement
description: New feature or improvement.
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |

        **REPLACE WITH ENHANCEMENT DETAILS** (Check below for guidelines)

        ---

        Detailed description.

        Reason for the change or new development.

        Acceptance criteria to verify the development. A list of requirements with the following format:

        `When *action* then *result*`

        For example:

        `When this is done then that other thing should happen`
