
name: Gradle

on:
  workflow_call:
    inputs:
      os:
        type: string
        description: OS used to run Gradle.
        default: ubuntu-latest

      ref:
        type: string
        description: Branch to check out.
        default: ${{ github.sha }}

      java:
        type: string
        description: Java version used to run Gradle.
        default: "17"

      java_distribution:
        type: string
        description: Java distribution used to run Gradle.
        default: temurin

      tasks:
        type: string
        description: Gradle tasks to execute.
        default: build

      check_directory:
        type: string
        description: Directory to check for build execution.
        default: build

# TODO Add 'ref' for 'nightly' and 'token' for write Git commands

jobs:
  gradle:
    name: Gradle ${{ inputs.tasks }}
    runs-on: ${{ inputs.os }}
#    permissions: read-all
    defaults:
      run: { shell: bash }
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java }}
          distribution: ${{ inputs.java_distribution }}
          cache: gradle
      - name: Build Project
        run: ./gradlew ${{ inputs.tasks }}
      - name: Diagnose Build
        if: failure()
        run: ./gradlew --info --stacktrace ${{ inputs.tasks }}
      - name: Check Build
        if: ${{ inputs.check_directory != '' }}
        run: ls -AlF "${{ inputs.check_directory }}"
