
name: Gradle

on:
  workflow_call:
    inputs:
      java:
        type: string
        description: Java version used to run Gradle.
        default: "17"

      java_distribution:
        type: string
        description: Java distribution used to run Gradle.
        default: temurin

      tasks:
        type: string
        description: Gradle tasks to execute.
        default: build

      check_directory:
        type: string
        description: Directory to check for build execution.
        default: build

jobs:
  gradle:
    name: Gradle ${{ inputs.tasks }}
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/gradle
        with:
          java: ${{ inputs.java }}
          java_distribution: ${{ inputs.java_distribution }}
          tasks: ${{ inputs.tasks }}
          check_directory: ${{ inputs.check_directory }}
