
name: Nightly

on:
  workflow_call:
    inputs:
      java:
        type: string
        description: Java version used to run Gradle.
        default: "17"

      java_distribution:
        type: string
        description: Java distribution used to run Gradle.
        default: temurin

      check_directory:
        type: string
        description: Directory to check for build execution.
        default: build

jobs:
  build:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Build Project
        uses: ./.github/actions/gradle
        with:
          java: ${{ inputs.java }}
          java_distribution: ${{ inputs.java_distribution }}
          check_directory: ${{ inputs.check_directory }}

  test_publishing:
    defaults:
      run: { shell: bash }
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    name: Test Publishing (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with: { ref: develop }
      - name: Test Publishing
        uses: ./.github/actions/gradle
        with:
          tasks: publishToMavenLocal -x test
          java: ${{ inputs.java }}
          java_distribution: ${{ inputs.java_distribution }}
          check_directory: ${{ inputs.check_directory }}
