
name: Pull Request

on:
  - pull_request

jobs:
  test_publishing:
    name: Test Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Test Publishing
        uses: ./.github/actions/gradle
        with:
          tasks: publishToMavenLocal -x test
